name: Publish Release

on:
  # The build will be triggered when we publish a release
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python 💻
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup Poetry 🔧
      uses: ThePalaceProject/circulation/.github/actions/poetry@main

    - name: Build & Publish 📚
      run: |
        VERSION="${{ github.ref_name }}"
        VERSION=${VERSION#"v"}
        echo "Version: $VERSION"
        poetry version "$VERSION"
        echo "__version__ = '$VERSION'" >> src/webpub_manifest_parser/_version.py
        poetry publish --build
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
